# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2022 Olesia Subbotina
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: pdd
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/pdd-action@master
