---
name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: g4s8/pdd-action@master
