---
name: pdd
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/pdd-action@master
